### PR TITLE
Add all DPE crates to a workspace

### PR DESCRIPTION
**Pull request by jhand2**
* Make a common workspace to make it easier to format/build all code at once.
* Set the rust version to a common version to ensure the same compiler is being used locally and in CI.

### CODE REVIEW

**Comment by zhalvorsen** [comment]
Have you tried this as part of the caliptra-sw repo? I've heard of problems with nested workspaces.

**Comment by hpya93** [comment]
I fixed this warning in openssl.rs (found in cicd job logs) and tried to build locally
```
error: length comparison to zero
  --> crypto/src/openssl.rs:23:25
   |
23 |         let e_code = if s.len() > 0 {
   |                         ^^^^^^^^^^^ help: using `!is_empty` is clearer and more explicit: `!s.is_empty()`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#len_zero
   = note: `-D clippy::len-zero` implied by `-D warnings`
```

The Rust build completed with warnings. The Go tests failed as simulator was not built.
```
# all "cargo build" , "clippy build", "cargo test" commands in ci.sh are giving this warning
unused manifest key: bin.0.target
```
I have never seen this warning earlier when CICD was working. Is it because of this warning simulator is not available at  ../simulator/target/debug/simulator?

**Review by zhalvorsen — DISMISSED** [review]
LGTM as long as it works with caliptra-sw

**Review by sree-revoori1 — APPROVED** [review]

**Comment by jhand2** [comment]
> LGTM as long as it works with caliptra-sw

Confirmed that this works. The DPE crates are already explicitly excluded from the Caliptra workspace, so there's not really any nesting.

**Review by sree-revoori1 — APPROVED** [review]

**Review by sree-revoori1 — APPROVED** [review]

**Pull request merged**
